name: Backend Route Tests

on:
  push:
    branches: [ main ]

jobs:
  test-backend-routes:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install EackEnd dependencies
      run: npm install
      working-directory: ./BackEnd

    - name: Run Tests
      run: npx cross-env NODE_ENV=test npm test
      working-directory: ./BackEnd